2021-12-09 17:19:42.957 +03:00 [INF] Application starting up
2021-12-09 17:21:26.545 +03:00 [WRN] User validation failed: DuplicateUserName.
2021-12-09 17:21:26.575 +03:00 [INF] HTTP POST /api/account/registration responded 200 in 1175.1455 ms
2021-12-09 17:21:41.280 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 25.9555 ms
2021-12-09 17:21:41.290 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 1.4037 ms
2021-12-09 17:21:45.460 +03:00 [INF] HTTP GET /api/users/2 responded 302 in 1.0217 ms
2021-12-09 17:21:45.466 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F2 responded 404 in 1.0708 ms
2021-12-09 17:21:49.183 +03:00 [INF] HTTP GET /api/users/3 responded 302 in 1.2158 ms
2021-12-09 17:21:49.190 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F3 responded 404 in 0.0867 ms
2021-12-09 17:21:52.445 +03:00 [INF] HTTP GET /api/users/4 responded 302 in 0.2029 ms
2021-12-09 17:21:52.455 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F4 responded 404 in 0.0841 ms
2021-12-09 17:21:57.175 +03:00 [INF] HTTP GET /api/users/5 responded 302 in 0.1695 ms
2021-12-09 17:21:57.180 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F5 responded 404 in 0.0846 ms
2021-12-09 17:22:00.726 +03:00 [INF] HTTP GET /api/users/6 responded 302 in 0.3016 ms
2021-12-09 17:22:00.731 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F6 responded 404 in 0.1077 ms
2021-12-09 17:22:03.157 +03:00 [INF] HTTP GET /api/users/7 responded 302 in 0.1507 ms
2021-12-09 17:22:03.162 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F7 responded 404 in 0.0837 ms
2021-12-09 17:22:05.391 +03:00 [INF] HTTP GET /api/users/8 responded 302 in 0.1895 ms
2021-12-09 17:22:05.396 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F8 responded 404 in 0.0809 ms
2021-12-09 17:22:06.753 +03:00 [INF] HTTP GET /api/users/9 responded 302 in 0.2203 ms
2021-12-09 17:22:06.758 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F9 responded 404 in 0.1116 ms
2021-12-09 17:22:07.956 +03:00 [INF] HTTP GET /api/users/10 responded 302 in 0.1792 ms
2021-12-09 17:22:07.961 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F10 responded 404 in 0.0922 ms
2021-12-09 17:22:09.232 +03:00 [INF] HTTP GET /api/users/11 responded 302 in 0.4808 ms
2021-12-09 17:22:09.260 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F11 responded 404 in 0.0954 ms
2021-12-09 17:22:10.559 +03:00 [INF] HTTP GET /api/users/12 responded 302 in 0.2726 ms
2021-12-09 17:22:10.570 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F12 responded 404 in 0.0877 ms
2021-12-09 17:22:12.178 +03:00 [INF] HTTP GET /api/users/13 responded 302 in 0.2138 ms
2021-12-09 17:22:12.182 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F13 responded 404 in 0.0701 ms
2021-12-09 17:22:13.075 +03:00 [INF] HTTP GET /api/users/14 responded 302 in 0.1888 ms
2021-12-09 17:22:13.081 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F14 responded 404 in 0.0961 ms
2021-12-09 17:22:14.190 +03:00 [INF] HTTP GET /api/users/15 responded 302 in 0.1909 ms
2021-12-09 17:22:14.195 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F15 responded 404 in 0.1521 ms
2021-12-09 17:22:15.267 +03:00 [INF] HTTP GET /api/users/16 responded 302 in 0.2717 ms
2021-12-09 17:22:15.273 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F16 responded 404 in 0.0646 ms
2021-12-09 17:22:16.331 +03:00 [INF] HTTP GET /api/users/17 responded 302 in 0.1614 ms
2021-12-09 17:22:16.340 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F17 responded 404 in 0.0809 ms
2021-12-09 17:22:17.368 +03:00 [INF] HTTP GET /api/users/18 responded 302 in 0.2147 ms
2021-12-09 17:22:17.373 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F18 responded 404 in 0.0419 ms
2021-12-09 17:22:18.758 +03:00 [INF] HTTP GET /api/users/19 responded 302 in 0.1305 ms
2021-12-09 17:22:18.762 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F19 responded 404 in 0.0492 ms
2021-12-09 17:22:21.176 +03:00 [INF] HTTP GET /api/users/20 responded 302 in 0.1603 ms
2021-12-09 17:22:21.181 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F20 responded 404 in 0.0667 ms
2021-12-09 17:22:22.151 +03:00 [INF] HTTP GET /api/users/21 responded 302 in 0.1279 ms
2021-12-09 17:22:22.156 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F21 responded 404 in 0.0601 ms
2021-12-09 17:22:23.127 +03:00 [INF] HTTP GET /api/users/22 responded 302 in 0.1472 ms
2021-12-09 17:22:23.132 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F22 responded 404 in 0.0575 ms
2021-12-09 17:22:25.043 +03:00 [INF] HTTP GET /api/users/23 responded 302 in 0.1526 ms
2021-12-09 17:22:25.048 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F23 responded 404 in 0.0452 ms
2021-12-09 17:22:25.860 +03:00 [INF] HTTP GET /api/users/24 responded 302 in 0.1471 ms
2021-12-09 17:22:25.865 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F24 responded 404 in 0.0545 ms
2021-12-09 17:22:27.383 +03:00 [INF] HTTP GET /api/users/25 responded 302 in 0.1781 ms
2021-12-09 17:22:27.389 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F25 responded 404 in 0.0460 ms
2021-12-09 17:22:28.425 +03:00 [INF] HTTP GET /api/users/26 responded 302 in 0.1497 ms
2021-12-09 17:22:28.430 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F26 responded 404 in 0.0597 ms
2021-12-09 17:22:29.335 +03:00 [INF] HTTP GET /api/users/27 responded 302 in 0.1405 ms
2021-12-09 17:22:29.360 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F27 responded 404 in 0.0824 ms
2021-12-09 17:22:30.242 +03:00 [INF] HTTP GET /api/users/28 responded 302 in 0.1182 ms
2021-12-09 17:22:30.247 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F28 responded 404 in 0.0792 ms
2021-12-09 17:22:31.345 +03:00 [INF] HTTP GET /api/users/29 responded 302 in 0.1215 ms
2021-12-09 17:22:31.350 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F29 responded 404 in 0.0418 ms
2021-12-09 17:22:32.495 +03:00 [INF] HTTP GET /api/users/230 responded 302 in 0.2400 ms
2021-12-09 17:22:32.501 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F230 responded 404 in 0.0619 ms
2021-12-09 17:22:35.008 +03:00 [INF] HTTP GET /api/users/30 responded 302 in 0.2083 ms
2021-12-09 17:22:35.013 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F30 responded 404 in 0.0559 ms
2021-12-09 17:22:46.343 +03:00 [ERR] User with the email UserEmail2@mail.ru was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the email UserEmail2@mail.ru was not found
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 102
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 48
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-09 17:22:46.436 +03:00 [INF] HTTP POST /api/account/sign-in responded 404 in 153.6893 ms
2021-12-09 17:23:35.250 +03:00 [ERR] User with the email UserEmail2@mail.ru was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the email UserEmail2@mail.ru was not found
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 102
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 48
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-09 17:23:35.269 +03:00 [INF] HTTP POST /api/account/sign-in responded 404 in 35.6312 ms
2021-12-09 17:24:28.329 +03:00 [WRN] Invalid password for user.
2021-12-09 17:24:28.334 +03:00 [WRN] User failed to provide the correct password.
2021-12-09 17:24:28.341 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 40.4060 ms
2021-12-09 17:25:13.970 +03:00 [WRN] Invalid password for user.
2021-12-09 17:25:13.972 +03:00 [WRN] User failed to provide the correct password.
2021-12-09 17:25:13.974 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 14.5823 ms
2021-12-09 17:26:17.495 +03:00 [INF] HTTP POST /api/account/registration responded 200 in 338.8530 ms
2021-12-09 17:27:07.097 +03:00 [INF] HTTP POST /api/account/sing-in responded 404 in 0.0918 ms
2021-12-09 17:27:44.610 +03:00 [INF] HTTP POST /api/account/sing-in responded 404 in 0.0643 ms
2021-12-09 17:29:39.177 +03:00 [INF] HTTP POST /api/account/registration responded 200 in 16.5229 ms
2021-12-09 17:31:11.055 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 362.1699 ms
2021-12-09 17:31:28.328 +03:00 [ERR] User with the identifier 1 was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the identifier 1 was not found
   at KudryavtsevAlexey.Forum.Services.Services.UserService.GetUserById(Int32 id) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\UserService.cs:line 39
   at KudryavtsevAlexey.Forum.Api.Controllers.UserController.GetUserById(Int32 id) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\UserController.cs:line 28
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-09 17:31:28.347 +03:00 [INF] HTTP GET /api/users/1 responded 404 in 38.3836 ms
2021-12-09 17:31:31.760 +03:00 [ERR] User with the identifier 2 was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the identifier 2 was not found
   at KudryavtsevAlexey.Forum.Services.Services.UserService.GetUserById(Int32 id) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\UserService.cs:line 39
   at KudryavtsevAlexey.Forum.Api.Controllers.UserController.GetUserById(Int32 id) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\UserController.cs:line 28
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-09 17:31:31.775 +03:00 [INF] HTTP GET /api/users/2 responded 404 in 17.3065 ms
2021-12-09 17:31:32.961 +03:00 [ERR] User with the identifier 3 was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the identifier 3 was not found
   at KudryavtsevAlexey.Forum.Services.Services.UserService.GetUserById(Int32 id) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\UserService.cs:line 39
   at KudryavtsevAlexey.Forum.Api.Controllers.UserController.GetUserById(Int32 id) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\UserController.cs:line 28
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-09 17:31:32.986 +03:00 [INF] HTTP GET /api/users/3 responded 404 in 29.2464 ms
2021-12-09 17:31:34.194 +03:00 [INF] HTTP GET /api/users/4 responded 200 in 148.3198 ms
2021-12-09 17:32:32.991 +03:00 [INF] HTTP GET /api/users/ responded 404 in 0.3828 ms
2021-12-09 17:32:44.930 +03:00 [INF] HTTP GET /api/accout/sign-in responded 404 in 0.2716 ms
2021-12-09 17:32:56.058 +03:00 [INF] HTTP GET /api/accout/sign-in responded 404 in 0.3378 ms
2021-12-09 17:33:05.272 +03:00 [INF] HTTP GET /api/accout/sign-out responded 404 in 0.5246 ms
2021-12-09 17:33:13.266 +03:00 [INF] HTTP GET /api/accout/sign-out responded 404 in 0.2754 ms
2021-12-09 17:33:22.338 +03:00 [INF] HTTP GET /api/accout/sign-out responded 404 in 0.4073 ms
2021-12-09 17:33:45.049 +03:00 [INF] HTTP GET /api/accout/sign-in responded 404 in 0.2504 ms
2021-12-09 17:34:19.739 +03:00 [INF] HTTP POST /api/accout/sign-in responded 404 in 0.3150 ms
2021-12-09 17:34:59.387 +03:00 [INF] HTTP POST /api/accout/sign-out responded 404 in 0.3117 ms
2021-12-09 17:35:39.425 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 88.2474 ms
2021-12-09 17:36:02.245 +03:00 [INF] HTTP GET /api/users/5 responded 200 in 3.2046 ms
2021-12-09 17:36:40.127 +03:00 [INF] HTTP GET /api/users/5 responded 200 in 1.9846 ms
2021-12-11 19:40:30.295 +03:00 [INF] Application starting up
2021-12-11 19:41:05.919 +03:00 [INF] HTTP POST /api/users/5 responded 405 in 104.9376 ms
2021-12-11 19:41:20.979 +03:00 [INF] HTTP POST /api/account/registration responded 400 in 827.2420 ms
2021-12-11 19:41:37.001 +03:00 [ERR] User with the userEmail CorrectUserEmail1@mail.ru was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the userEmail CorrectUserEmail1@mail.ru was not found
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 102
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:41:37.107 +03:00 [INF] HTTP POST /api/account/sign-in responded 404 in 261.7130 ms
2021-12-11 19:42:42.723 +03:00 [ERR] User with the userEmail CorrectUserEmail123@mail.ru was not found
KudryavtsevAlexey.Forum.Domain.CustomExceptions.UserNotFoundException: User with the userEmail CorrectUserEmail123@mail.ru was not found
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 102
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:42:42.744 +03:00 [INF] HTTP POST /api/account/sign-in responded 404 in 86.0006 ms
2021-12-11 19:42:49.757 +03:00 [INF] HTTP POST /api/account/registration responded 200 in 268.5187 ms
2021-12-11 19:43:42.557 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 14.2406 ms
2021-12-11 19:43:42.565 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.1503 ms
2021-12-11 19:43:45.259 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.6146 ms
2021-12-11 19:43:45.265 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.0951 ms
2021-12-11 19:43:46.114 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.7952 ms
2021-12-11 19:43:46.122 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.0981 ms
2021-12-11 19:43:46.745 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.2496 ms
2021-12-11 19:43:46.759 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.0772 ms
2021-12-11 19:43:47.278 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.2926 ms
2021-12-11 19:43:47.283 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.0877 ms
2021-12-11 19:43:47.994 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.1681 ms
2021-12-11 19:43:48.000 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.0774 ms
2021-12-11 19:43:48.648 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.1671 ms
2021-12-11 19:43:48.655 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.0805 ms
2021-12-11 19:43:52.133 +03:00 [INF] HTTP GET /api/users/2 responded 302 in 0.2040 ms
2021-12-11 19:43:52.147 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F2 responded 404 in 0.1290 ms
2021-12-11 19:43:55.096 +03:00 [INF] HTTP GET /api/users/3 responded 302 in 0.2080 ms
2021-12-11 19:43:55.105 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F3 responded 404 in 0.0877 ms
2021-12-11 19:43:59.258 +03:00 [INF] HTTP GET /api/users/4 responded 302 in 1.1183 ms
2021-12-11 19:43:59.272 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F4 responded 404 in 0.0877 ms
2021-12-11 19:44:00.659 +03:00 [INF] HTTP GET /api/users/5 responded 302 in 0.2111 ms
2021-12-11 19:44:00.665 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F5 responded 404 in 0.0880 ms
2021-12-11 19:44:01.791 +03:00 [INF] HTTP GET /api/users/6 responded 302 in 0.1650 ms
2021-12-11 19:44:01.796 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F6 responded 404 in 0.0900 ms
2021-12-11 19:44:02.991 +03:00 [INF] HTTP GET /api/users/7 responded 302 in 0.1513 ms
2021-12-11 19:44:02.997 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F7 responded 404 in 0.1886 ms
2021-12-11 19:44:04.167 +03:00 [INF] HTTP GET /api/users/8 responded 302 in 0.2440 ms
2021-12-11 19:44:04.175 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F8 responded 404 in 0.0638 ms
2021-12-11 19:44:05.015 +03:00 [INF] HTTP GET /api/users/9 responded 302 in 0.1266 ms
2021-12-11 19:44:05.021 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F9 responded 404 in 0.1380 ms
2021-12-11 19:44:06.225 +03:00 [INF] HTTP GET /api/users/10 responded 302 in 0.2656 ms
2021-12-11 19:44:06.231 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F10 responded 404 in 0.0464 ms
2021-12-11 19:44:07.059 +03:00 [INF] HTTP GET /api/users/11 responded 302 in 0.1395 ms
2021-12-11 19:44:07.063 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F11 responded 404 in 0.0690 ms
2021-12-11 19:44:07.990 +03:00 [INF] HTTP GET /api/users/12 responded 302 in 0.1382 ms
2021-12-11 19:44:07.995 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F12 responded 404 in 0.1630 ms
2021-12-11 19:44:08.731 +03:00 [INF] HTTP GET /api/users/13 responded 302 in 0.1504 ms
2021-12-11 19:44:08.737 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F13 responded 404 in 0.0618 ms
2021-12-11 19:44:09.564 +03:00 [INF] HTTP GET /api/users/14 responded 302 in 0.1565 ms
2021-12-11 19:44:09.569 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F14 responded 404 in 0.0831 ms
2021-12-11 19:44:10.563 +03:00 [INF] HTTP GET /api/users/15/ responded 302 in 0.1146 ms
2021-12-11 19:44:10.568 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F15%2F responded 404 in 0.0476 ms
2021-12-11 19:44:12.991 +03:00 [INF] HTTP GET /api/users/15 responded 302 in 0.1780 ms
2021-12-11 19:44:12.996 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F15 responded 404 in 0.0606 ms
2021-12-11 19:44:13.998 +03:00 [INF] HTTP GET /api/users/16 responded 302 in 0.1194 ms
2021-12-11 19:44:14.004 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F16 responded 404 in 0.0978 ms
2021-12-11 19:44:14.983 +03:00 [INF] HTTP GET /api/users/17 responded 302 in 0.2728 ms
2021-12-11 19:44:14.991 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F17 responded 404 in 0.0555 ms
2021-12-11 19:44:15.792 +03:00 [INF] HTTP GET /api/users/18 responded 302 in 0.1198 ms
2021-12-11 19:44:15.797 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F18 responded 404 in 0.0774 ms
2021-12-11 19:44:17.363 +03:00 [INF] HTTP GET /api/users/19 responded 302 in 0.1415 ms
2021-12-11 19:44:17.369 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F19 responded 404 in 0.0837 ms
2021-12-11 19:44:34.865 +03:00 [INF] HTTP GET /api/account/sign-in responded 405 in 0.0900 ms
2021-12-11 19:44:37.822 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:44:37.847 +03:00 [ERR] Data is Null. This method or property cannot be called on Null values.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 98
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:44:37.892 +03:00 [ERR] HTTP POST /api/account/sign-in responded 500 in 93.1370 ms
2021-12-11 19:44:59.570 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:44:59.583 +03:00 [ERR] Data is Null. This method or property cannot be called on Null values.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 98
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:44:59.614 +03:00 [ERR] HTTP POST /api/account/sign-in responded 500 in 45.8810 ms
2021-12-11 19:45:22.667 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:45:22.679 +03:00 [ERR] Data is Null. This method or property cannot be called on Null values.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 98
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:45:22.707 +03:00 [ERR] HTTP POST /api/account/sign-in responded 500 in 43.3875 ms
2021-12-11 19:46:05.587 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:46:05.600 +03:00 [ERR] Data is Null. This method or property cannot be called on Null values.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 98
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:46:05.630 +03:00 [ERR] HTTP POST /api/account/sign-in responded 500 in 47.7271 ms
2021-12-11 19:46:19.057 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:46:19.070 +03:00 [ERR] Data is Null. This method or property cannot be called on Null values.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 98
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:46:19.102 +03:00 [ERR] HTTP POST /api/account/sign-in responded 500 in 49.3071 ms
2021-12-11 19:46:46.703 +03:00 [INF] HTTP POST /api/account/registration responded 200 in 25.2225 ms
2021-12-11 19:47:09.012 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:47:09.025 +03:00 [ERR] Data is Null. This method or property cannot be called on Null values.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at lambda_method150(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 98
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.SignIn(SignInUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 19:47:09.058 +03:00 [ERR] HTTP POST /api/account/sign-in responded 500 in 47.8292 ms
2021-12-11 19:47:44.320 +03:00 [INF] Application starting up
2021-12-11 19:48:53.305 +03:00 [INF] HTTP POST /account/sign-in responded 404 in 95.6621 ms
2021-12-11 19:49:28.972 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method30(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method30(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:50:06.169 +03:00 [INF] Application starting up
2021-12-11 19:50:51.191 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method30(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
   at Microsoft.Data.SqlClient.SqlBuffer.get_String()
   at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method30(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-12-11 19:51:10.113 +03:00 [INF] Application starting up
2021-12-11 19:58:28.941 +03:00 [INF] Application starting up
2021-12-11 19:59:44.878 +03:00 [INF] HTTP POST /account/registration responded 404 in 88.3977 ms
2021-12-11 20:00:24.854 +03:00 [ERR] Failed executing DbCommand (18ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000), @p2='?' (Size = 256), @p3='?' (DbType = Boolean), @p4='?' (DbType = DateTime2), @p5='?' (Size = 4000), @p6='?' (DbType = Boolean), @p7='?' (DbType = DateTimeOffset), @p8='?' (Size = 4000), @p9='?' (Size = 256), @p10='?' (Size = 256), @p11='?' (DbType = Int32), @p12='?' (Size = 4000), @p13='?' (Size = 4000), @p14='?' (DbType = Boolean), @p15='?' (Size = 4000), @p16='?' (Size = 4000), @p17='?' (DbType = Boolean), @p18='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AspNetUsers] ([AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [JoinedAt], [Location], [LockoutEnabled], [LockoutEnd], [Name], [NormalizedEmail], [NormalizedUserName], [OrganizationId], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [Summary], [TwoFactorEnabled], [UserName])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18);
SELECT [Id]
FROM [AspNetUsers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2021-12-11 20:00:24.952 +03:00 [ERR] An exception occurred in the database while saving changes for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:99e6bf63-62f5-4aa1-ab5e-a8f0e43cb599
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:99e6bf63-62f5-4aa1-ab5e-a8f0e43cb599
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2021-12-11 20:00:25.640 +03:00 [ERR] An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:99e6bf63-62f5-4aa1-ab5e-a8f0e43cb599
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.CreateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 93
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 20:00:25.786 +03:00 [ERR] HTTP POST /api/account/registration responded 500 in 2362.7231 ms
2021-12-11 20:01:04.037 +03:00 [ERR] Failed executing DbCommand (7ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000), @p2='?' (Size = 256), @p3='?' (DbType = Boolean), @p4='?' (DbType = DateTime2), @p5='?' (Size = 4000), @p6='?' (DbType = Boolean), @p7='?' (DbType = DateTimeOffset), @p8='?' (Size = 4000), @p9='?' (Size = 256), @p10='?' (Size = 256), @p11='?' (DbType = Int32), @p12='?' (Size = 4000), @p13='?' (Size = 4000), @p14='?' (DbType = Boolean), @p15='?' (Size = 4000), @p16='?' (Size = 4000), @p17='?' (DbType = Boolean), @p18='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AspNetUsers] ([AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [JoinedAt], [Location], [LockoutEnabled], [LockoutEnd], [Name], [NormalizedEmail], [NormalizedUserName], [OrganizationId], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [Summary], [TwoFactorEnabled], [UserName])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18);
SELECT [Id]
FROM [AspNetUsers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2021-12-11 20:01:04.050 +03:00 [ERR] An exception occurred in the database while saving changes for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:99e6bf63-62f5-4aa1-ab5e-a8f0e43cb599
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:99e6bf63-62f5-4aa1-ab5e-a8f0e43cb599
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2021-12-11 20:01:04.589 +03:00 [ERR] An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:99e6bf63-62f5-4aa1-ab5e-a8f0e43cb599
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.CreateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 93
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 20:01:04.642 +03:00 [ERR] HTTP POST /api/account/registration responded 500 in 770.8742 ms
2021-12-11 20:03:14.912 +03:00 [INF] Application starting up
2021-12-11 20:08:37.432 +03:00 [INF] Application starting up
2021-12-11 20:09:10.657 +03:00 [ERR] Failed executing DbCommand (11ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000), @p2='?' (Size = 256), @p3='?' (DbType = Boolean), @p4='?' (DbType = DateTime2), @p5='?' (Size = 4000), @p6='?' (DbType = Boolean), @p7='?' (DbType = DateTimeOffset), @p8='?' (Size = 4000), @p9='?' (Size = 256), @p10='?' (Size = 256), @p11='?' (DbType = Int32), @p12='?' (Size = 4000), @p13='?' (Size = 4000), @p14='?' (DbType = Boolean), @p15='?' (Size = 4000), @p16='?' (Size = 4000), @p17='?' (DbType = Boolean), @p18='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AspNetUsers] ([AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [JoinedAt], [Location], [LockoutEnabled], [LockoutEnd], [Name], [NormalizedEmail], [NormalizedUserName], [OrganizationId], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [Summary], [TwoFactorEnabled], [UserName])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18);
SELECT [Id]
FROM [AspNetUsers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2021-12-11 20:09:10.741 +03:00 [ERR] An exception occurred in the database while saving changes for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:a7458059-82bc-4cbf-81a0-1581f15cacbf
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:a7458059-82bc-4cbf-81a0-1581f15cacbf
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2021-12-11 20:09:20.241 +03:00 [ERR] An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:a7458059-82bc-4cbf-81a0-1581f15cacbf
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.CreateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 93
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 20:13:42.828 +03:00 [INF] Application starting up
2021-12-11 20:15:01.262 +03:00 [ERR] Failed executing DbCommand (16ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000), @p2='?' (Size = 256), @p3='?' (DbType = Boolean), @p4='?' (DbType = DateTime2), @p5='?' (Size = 4000), @p6='?' (DbType = Boolean), @p7='?' (DbType = DateTimeOffset), @p8='?' (Size = 4000), @p9='?' (Size = 256), @p10='?' (Size = 256), @p11='?' (DbType = Int32), @p12='?' (Size = 4000), @p13='?' (Size = 4000), @p14='?' (DbType = Boolean), @p15='?' (Size = 4000), @p16='?' (Size = 4000), @p17='?' (DbType = Boolean), @p18='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AspNetUsers] ([AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [JoinedAt], [Location], [LockoutEnabled], [LockoutEnd], [Name], [NormalizedEmail], [NormalizedUserName], [OrganizationId], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [Summary], [TwoFactorEnabled], [UserName])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18);
SELECT [Id]
FROM [AspNetUsers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2021-12-11 20:15:01.334 +03:00 [ERR] An exception occurred in the database while saving changes for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:3f442229-6315-4017-9b22-6671154bc06e
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:3f442229-6315-4017-9b22-6671154bc06e
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2021-12-11 20:15:09.564 +03:00 [ERR] An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:3f442229-6315-4017-9b22-6671154bc06e
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.CreateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 93
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 20:17:28.902 +03:00 [INF] Application starting up
2021-12-11 20:17:59.882 +03:00 [ERR] Failed executing DbCommand (9ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000), @p2='?' (Size = 256), @p3='?' (DbType = Boolean), @p4='?' (DbType = DateTime2), @p5='?' (Size = 4000), @p6='?' (DbType = Boolean), @p7='?' (DbType = DateTimeOffset), @p8='?' (Size = 4000), @p9='?' (Size = 256), @p10='?' (Size = 256), @p11='?' (DbType = Int32), @p12='?' (Size = 4000), @p13='?' (Size = 4000), @p14='?' (DbType = Boolean), @p15='?' (Size = 4000), @p16='?' (Size = 4000), @p17='?' (DbType = Boolean), @p18='?' (Size = 256)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [AspNetUsers] ([AccessFailedCount], [ConcurrencyStamp], [Email], [EmailConfirmed], [JoinedAt], [Location], [LockoutEnabled], [LockoutEnd], [Name], [NormalizedEmail], [NormalizedUserName], [OrganizationId], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [SecurityStamp], [Summary], [TwoFactorEnabled], [UserName])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18);
SELECT [Id]
FROM [AspNetUsers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2021-12-11 20:17:59.935 +03:00 [ERR] An exception occurred in the database while saving changes for context type 'KudryavtsevAlexey.Forum.Infrastructure.Database.ForumDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:21881c4a-bd1f-478b-a1b6-825a0dc5ae8b
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:21881c4a-bd1f-478b-a1b6-825a0dc5ae8b
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2021-12-11 20:18:05.069 +03:00 [ERR] An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Summary', table 'Forum.dbo.AspNetUsers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:21881c4a-bd1f-478b-a1b6-825a0dc5ae8b
Error Number:515,State:2,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.CreateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at KudryavtsevAlexey.Forum.Services.Services.AccountService.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Services\Services\AccountService.cs:line 93
   at KudryavtsevAlexey.Forum.Api.Controllers.AccountController.Register(RegisterUserDto userDto) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Controllers\AccountController.cs:line 33
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at KudryavtsevAlexey.Forum.Api.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\Lenovo\source\repos\KudryavtsevAlexey.Forum\KudryavtsevAlexey.Forum.Api\Middlewares\ExceptionHandlingMiddleware.cs:line 21
2021-12-11 20:19:57.667 +03:00 [INF] Application starting up
2021-12-11 20:21:10.710 +03:00 [INF] HTTP POST /api/account/registration responded 200 in 56084.1260 ms
2021-12-11 20:21:33.454 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 32.4085 ms
2021-12-11 20:21:33.472 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 1.2347 ms
2021-12-11 20:21:47.506 +03:00 [INF] HTTP GET /api/users/1 responded 302 in 0.9063 ms
2021-12-11 20:21:47.527 +03:00 [INF] HTTP GET /Account/Login?ReturnUrl=%2Fapi%2Fusers%2F1 responded 404 in 0.8352 ms
2021-12-11 20:24:56.826 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 152899.7913 ms
2021-12-11 20:25:52.841 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 236.7578 ms
2021-12-11 20:26:19.025 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 62.3181 ms
2021-12-11 20:32:06.620 +03:00 [INF] HTTP GET /api/users/sign-out responded 400 in 32.7944 ms
2021-12-11 20:32:14.405 +03:00 [INF] HTTP POST /api/users/sign-out responded 405 in 4.9767 ms
2021-12-11 20:32:48.727 +03:00 [INF] HTTP POST /api/users/sign-out responded 405 in 0.4187 ms
2021-12-11 20:33:00.178 +03:00 [INF] HTTP POST /api/account/sign-out responded 200 in 39.7541 ms
2021-12-11 20:33:12.907 +03:00 [INF] HTTP POST /api/account/sign-in responded 415 in 9.9295 ms
2021-12-11 20:33:58.219 +03:00 [INF] HTTP POST /api/account/sign-in responded 415 in 27.3925 ms
2021-12-11 20:34:27.965 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 23347.0011 ms
2021-12-11 20:34:46.580 +03:00 [INF] HTTP POST /api/users/1 responded 405 in 1.0226 ms
2021-12-11 20:35:16.664 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 26801.1392 ms
2021-12-11 20:36:19.193 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 47.2133 ms
2021-12-11 20:39:30.051 +03:00 [INF] HTTP GET /api/account/sign-in responded 405 in 22.4696 ms
2021-12-11 20:39:43.322 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 6152.6895 ms
2021-12-11 21:03:26.529 +03:00 [INF] Application starting up
2021-12-11 21:04:02.859 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 1562.0956 ms
2021-12-11 21:04:23.492 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 11.6870 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: OAuthJwt, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:04:23.542 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: OAuthJwt, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:09:58.179 +03:00 [INF] Application starting up
2021-12-11 21:10:16.338 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 72.5895 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:10:16.378 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:10:56.563 +03:00 [INF] HTTP GET /api/account/sign-in responded 405 in 8.2330 ms
2021-12-11 21:11:01.937 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 1349.1520 ms
2021-12-11 21:11:10.855 +03:00 [INF] HTTP POST /api/users/1 responded 405 in 1.4219 ms
2021-12-11 21:11:13.467 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 8.4588 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:11:13.490 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:11:17.890 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 1.1367 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:11:17.902 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:11:24.103 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 0.5495 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:11:24.113 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:11:24.933 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 0.7436 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:11:24.940 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:11:25.582 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 0.6378 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:11:25.591 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:11:57.997 +03:00 [INF] Application starting up
2021-12-11 21:12:08.161 +03:00 [INF] Application starting up
2021-12-11 21:12:16.645 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 68.8280 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:12:16.682 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:12:21.597 +03:00 [ERR] HTTP GET /api/users/1 responded 500 in 6.3523 ms
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2021-12-11 21:12:21.613 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: JwtBearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-12-11 21:13:26.567 +03:00 [INF] Application starting up
2021-12-11 21:13:36.419 +03:00 [INF] HTTP GET /api/account/sign-out responded 405 in 68.0414 ms
2021-12-11 21:13:39.703 +03:00 [INF] HTTP POST /api/account/sign-out responded 200 in 560.5872 ms
2021-12-11 21:13:53.702 +03:00 [INF] HTTP POST /api/account/sign-in responded 200 in 853.2595 ms
2021-12-11 21:14:12.427 +03:00 [INF] HTTP POST /api/users/1 responded 405 in 29.1835 ms
2021-12-11 21:14:15.459 +03:00 [INF] HTTP GET /api/users/1 responded 401 in 26.4819 ms
2021-12-11 21:14:27.662 +03:00 [INF] HTTP GET /api/users/1 responded 401 in 1.2719 ms
2021-12-11 21:14:39.026 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 291.3856 ms
2021-12-11 21:17:03.830 +03:00 [INF] Application starting up
2021-12-11 21:17:37.302 +03:00 [INF] Application starting up
2021-12-11 21:17:51.525 +03:00 [INF] HTTP GET /api/account/sign-out responded 405 in 78.3311 ms
2021-12-11 21:17:56.955 +03:00 [INF] HTTP POST /api/account/sign-out responded 200 in 530.9405 ms
2021-12-11 21:18:04.196 +03:00 [INF] HTTP POST /api/users/1 responded 405 in 1.3759 ms
2021-12-11 21:18:08.237 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 798.0798 ms
2021-12-11 21:18:19.961 +03:00 [INF] HTTP GET /api/users/1 responded 401 in 5.8660 ms
2021-12-11 21:18:25.929 +03:00 [INF] HTTP GET /api/users/1 responded 401 in 0.8651 ms
2021-12-11 21:18:29.303 +03:00 [INF] HTTP GET /api/users/1 responded 200 in 61.7438 ms
2021-12-11 21:18:44.799 +03:00 [INF] HTTP GET /api/account/sign-out responded 405 in 0.1083 ms
2021-12-11 21:36:48.513 +03:00 [INF] Application starting up
